from django.urls import path

from dav.views import (
    CalendarCollectionUidView,
    CalendarCollectionView,
    CalendarHomeUidView,
    CalendarHomeView,
    CalendarObjectUidView,
    CalendarObjectView,
    CalendarsCollectionView,
    CalendarsUidsCollectionView,
    CalendarsUsersCollectionView,
    DavRootView,
    PrincipalUidView,
    PrincipalView,
    PrincipalsCollectionView,
    PrincipalsUsersCollectionView,
)

app_name = "dav"

urlpatterns = [
    path("", DavRootView.as_view(), name="root"),
    path(
        "principals",
        PrincipalsCollectionView.as_view(),
        name="principals-no-slash",
    ),
    path("principals/", PrincipalsCollectionView.as_view(), name="principals"),
    path(
        "principals/users",
        PrincipalsUsersCollectionView.as_view(),
        name="principals-users-no-slash",
    ),
    path(
        "principals/users/",
        PrincipalsUsersCollectionView.as_view(),
        name="principals-users",
    ),
    path(
        "principals/users/<str:username>",
        PrincipalView.as_view(),
        name="principal-user-no-slash",
    ),
    path(
        "principals/users/<str:username>/",
        PrincipalView.as_view(),
        name="principal-user",
    ),
    path(
        "principals/__uids__/<str:guid>",
        PrincipalUidView.as_view(),
        name="principal-uid-no-slash",
    ),
    path(
        "principals/__uids__/<str:guid>/",
        PrincipalUidView.as_view(),
        name="principal-uid",
    ),
    path(
        "principals/<str:username>",
        PrincipalView.as_view(),
        name="principal-no-slash",
    ),
    path("principals/<str:username>/", PrincipalView.as_view(), name="principal"),
    path(
        "calendars",
        CalendarsCollectionView.as_view(),
        name="calendars-no-slash",
    ),
    path("calendars/", CalendarsCollectionView.as_view(), name="calendars"),
    path(
        "calendars//",
        CalendarsCollectionView.as_view(),
        name="calendars-double-slash",
    ),
    path(
        "calendars/__uids__",
        CalendarsUidsCollectionView.as_view(),
        name="calendars-uids-no-slash",
    ),
    path(
        "calendars/__uids__/",
        CalendarsUidsCollectionView.as_view(),
        name="calendars-uids",
    ),
    path(
        "calendars/users",
        CalendarsUsersCollectionView.as_view(),
        name="calendars-users-no-slash",
    ),
    path(
        "calendars/users/",
        CalendarsUsersCollectionView.as_view(),
        name="calendars-users",
    ),
    path(
        "calendars/users/<str:username>",
        CalendarHomeView.as_view(),
        name="calendar-home-users-no-slash",
    ),
    path(
        "calendars/users/<str:username>/",
        CalendarHomeView.as_view(),
        name="calendar-home-users",
    ),
    path(
        "calendars/__uids__/<str:guid>",
        CalendarHomeUidView.as_view(),
        name="calendar-home-uid-no-slash",
    ),
    path(
        "calendars/__uids__/<str:guid>/",
        CalendarHomeUidView.as_view(),
        name="calendar-home-uid",
    ),
    path(
        "calendars/<str:username>",
        CalendarHomeView.as_view(),
        name="calendar-home-no-slash",
    ),
    path(
        "calendars/<str:username>/",
        CalendarHomeView.as_view(),
        name="calendar-home",
    ),
    path(
        "calendars/users/<str:username>/<slug:slug>",
        CalendarCollectionView.as_view(),
        name="calendar-collection-users-no-slash",
    ),
    path(
        "calendars/users/<str:username>/<slug:slug>/",
        CalendarCollectionView.as_view(),
        name="calendar-collection-users",
    ),
    path(
        "calendars/__uids__/<str:guid>/<slug:slug>",
        CalendarCollectionUidView.as_view(),
        name="calendar-collection-uid-no-slash",
    ),
    path(
        "calendars/__uids__/<str:guid>/<slug:slug>/",
        CalendarCollectionUidView.as_view(),
        name="calendar-collection-uid",
    ),
    path(
        "calendars/<str:username>/<slug:slug>",
        CalendarCollectionView.as_view(),
        name="calendar-collection-no-slash",
    ),
    path(
        "calendars/<str:username>/<slug:slug>/",
        CalendarCollectionView.as_view(),
        name="calendar-collection",
    ),
    path(
        "calendars/users/<str:username>/<slug:slug>/<path:filename>",
        CalendarObjectView.as_view(),
        name="calendar-object-users",
    ),
    path(
        "calendars/__uids__/<str:guid>/<slug:slug>/<path:filename>",
        CalendarObjectUidView.as_view(),
        name="calendar-object-uid",
    ),
    path(
        "calendars/<str:username>/<slug:slug>/<path:filename>",
        CalendarObjectView.as_view(),
        name="calendar-object",
    ),
]
