from django.urls import path

from dav.views import (
    CalendarCollectionUidView,
    CalendarCollectionView,
    CalendarHomeUidView,
    CalendarHomeView,
    CalendarObjectUidView,
    CalendarObjectView,
    DavRootView,
    PrincipalUidView,
    PrincipalView,
    PrincipalsCollectionView,
)

app_name = "dav"

urlpatterns = [
    path("", DavRootView.as_view(), name="root"),
    path(
        "principals",
        PrincipalsCollectionView.as_view(),
        name="principals-no-slash",
    ),
    path("principals/", PrincipalsCollectionView.as_view(), name="principals"),
    path(
        "principals/users",
        PrincipalsCollectionView.as_view(
            href="/dav/principals/users/",
            display_name="users",
        ),
        name="principals-users-no-slash",
    ),
    path(
        "principals/users/",
        PrincipalsCollectionView.as_view(
            href="/dav/principals/users/",
            display_name="users",
        ),
        name="principals-users",
    ),
    path(
        "principals/users/<str:username>",
        PrincipalView.as_view(),
        name="principal-user-no-slash",
    ),
    path(
        "principals/users/<str:username>/",
        PrincipalView.as_view(),
        name="principal-user",
    ),
    path(
        "principals/__uids__/<str:guid>",
        PrincipalUidView.as_view(),
        name="principal-uid-no-slash",
    ),
    path(
        "principals/__uids__/<str:guid>/",
        PrincipalUidView.as_view(),
        name="principal-uid",
    ),
    path(
        "principals/<str:username>",
        PrincipalView.as_view(),
        name="principal-no-slash",
    ),
    path("principals/<str:username>/", PrincipalView.as_view(), name="principal"),
    path(
        "calendars",
        PrincipalsCollectionView.as_view(
            href="/dav/calendars/",
            display_name="calendars",
        ),
        name="calendars-no-slash",
    ),
    path(
        "calendars/",
        PrincipalsCollectionView.as_view(
            href="/dav/calendars/",
            display_name="calendars",
        ),
        name="calendars",
    ),
    path(
        "calendars//",
        PrincipalsCollectionView.as_view(
            href="/dav/calendars/",
            display_name="calendars",
        ),
        name="calendars-double-slash",
    ),
    path(
        "calendars/__uids__",
        PrincipalsCollectionView.as_view(
            href="/dav/calendars/__uids__/",
            display_name="uid calendars",
        ),
        name="calendars-uids-no-slash",
    ),
    path(
        "calendars/__uids__/",
        PrincipalsCollectionView.as_view(
            href="/dav/calendars/__uids__/",
            display_name="uid calendars",
        ),
        name="calendars-uids",
    ),
    path(
        "calendars/users",
        PrincipalsCollectionView.as_view(
            href="/dav/calendars/users/",
            display_name="user calendars",
        ),
        name="calendars-users-no-slash",
    ),
    path(
        "calendars/users/",
        PrincipalsCollectionView.as_view(
            href="/dav/calendars/users/",
            display_name="user calendars",
        ),
        name="calendars-users",
    ),
    path(
        "calendars/users/<str:username>",
        CalendarHomeView.as_view(),
        name="calendar-home-users-no-slash",
    ),
    path(
        "calendars/users/<str:username>/",
        CalendarHomeView.as_view(),
        name="calendar-home-users",
    ),
    path(
        "calendars/__uids__/<str:guid>",
        CalendarHomeUidView.as_view(),
        name="calendar-home-uid-no-slash",
    ),
    path(
        "calendars/__uids__/<str:guid>/",
        CalendarHomeUidView.as_view(),
        name="calendar-home-uid",
    ),
    path(
        "calendars/<str:username>",
        CalendarHomeView.as_view(),
        name="calendar-home-no-slash",
    ),
    path(
        "calendars/<str:username>/",
        CalendarHomeView.as_view(),
        name="calendar-home",
    ),
    path(
        "calendars/users/<str:username>/<slug:slug>",
        CalendarCollectionView.as_view(),
        name="calendar-collection-users-no-slash",
    ),
    path(
        "calendars/users/<str:username>/<slug:slug>/",
        CalendarCollectionView.as_view(),
        name="calendar-collection-users",
    ),
    path(
        "calendars/__uids__/<str:guid>/<slug:slug>",
        CalendarCollectionUidView.as_view(),
        name="calendar-collection-uid-no-slash",
    ),
    path(
        "calendars/__uids__/<str:guid>/<slug:slug>/",
        CalendarCollectionUidView.as_view(),
        name="calendar-collection-uid",
    ),
    path(
        "calendars/<str:username>/<slug:slug>",
        CalendarCollectionView.as_view(),
        name="calendar-collection-no-slash",
    ),
    path(
        "calendars/<str:username>/<slug:slug>/",
        CalendarCollectionView.as_view(),
        name="calendar-collection",
    ),
    path(
        "calendars/users/<str:username>/<slug:slug>/<path:filename>",
        CalendarObjectView.as_view(),
        name="calendar-object-users",
    ),
    path(
        "calendars/__uids__/<str:guid>/<slug:slug>/<path:filename>",
        CalendarObjectUidView.as_view(),
        name="calendar-object-uid",
    ),
    path(
        "calendars/<str:username>/<slug:slug>/<path:filename>",
        CalendarObjectView.as_view(),
        name="calendar-object",
    ),
]
