# Generated by Django 6.0.2 on 2026-02-16 03:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(blank=True, max_length=16)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_calendars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "slug"],
            },
        ),
        migrations.CreateModel(
            name="CalendarObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=255)),
                ("filename", models.CharField(max_length=255)),
                ("etag", models.CharField(max_length=128)),
                ("ical_blob", models.TextField()),
                (
                    "content_type",
                    models.CharField(
                        default="text/calendar; charset=utf-8", max_length=128
                    ),
                ),
                ("size", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_objects",
                        to="calendars.calendar",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalendarShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("read", "Read"),
                            ("write", "Write"),
                            ("admin", "Admin"),
                        ],
                        default="read",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="calendars.calendar",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="calendar",
            constraint=models.UniqueConstraint(
                fields=("owner", "slug"), name="uniq_calendar_owner_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarobject",
            constraint=models.UniqueConstraint(
                fields=("calendar", "uid"), name="uniq_calendar_object_uid"
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarobject",
            constraint=models.UniqueConstraint(
                fields=("calendar", "filename"), name="uniq_calendar_object_filename"
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarshare",
            constraint=models.UniqueConstraint(
                fields=("calendar", "user"), name="uniq_calendar_share"
            ),
        ),
    ]
