# Generated by Django 6.0.2 on 2026-02-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarshare',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
