# Generated by Django 6.0.2 on 2026-02-17 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendars", "0002_calendarshare_accepted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarObjectChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveBigIntegerField()),
                ("filename", models.CharField(max_length=255)),
                ("uid", models.CharField(blank=True, max_length=255, null=True)),
                ("is_deleted", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_changes",
                        to="calendars.calendar",
                    ),
                ),
            ],
            options={
                "ordering": ["calendar_id", "revision"],
                "indexes": [
                    models.Index(
                        fields=["calendar", "filename"],
                        name="idx_calendar_change_filename",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("calendar", "revision"),
                        name="uniq_calendar_change_revision",
                    )
                ],
            },
        ),
    ]
