# Generated by Django 6.0.2 on 2026-02-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_calendar_component_kind_calendar_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarobject',
            name='dead_properties',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
