# syntax=docker/dockerfile:1

FROM rust:1-bookworm

WORKDIR /app

COPY . .

ENV SQLX_OFFLINE=true
ENV PORT=8000

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/app/target \
    cargo build --release && \
    cp /app/target/release/davhome /usr/local/bin/davhome

CMD ["/usr/local/bin/davhome"]
